import poster1 from '../assets/image/poster/1.jpg';
import poster2 from '../assets/image/poster/2.jpg';
import poster3 from '../assets/image/poster/3.jpg';
import poster4 from '../assets/image/poster/4.jpg';
import poster5 from '../assets/image/poster/5.jpg';
import poster6 from '../assets/image/poster/6.jpg';
import poster7 from '../assets/image/poster/7.jpg';
import poster8 from '../assets/image/poster/8.jpg';
import poster9 from '../assets/image/poster/9.jpg';
import poster10 from '../assets/image/poster/10.jpg';
import scene1 from '../assets/image/scene/1_scene.jpg';
import scene2 from '../assets/image/scene/2_scene.jpg';
import scene3 from '../assets/image/scene/3_scene.jpg';
import scene4 from '../assets/image/scene/4_scene.jpg';
import scene5 from '../assets/image/scene/5_scene.jpg';
import scene6 from '../assets/image/scene/6_scene.jpg';
import scene7 from '../assets/image/scene/7_scene.jpg';
import scene8 from '../assets/image/scene/8_scene.jpg';
import scene9 from '../assets/image/scene/9_scene.jpg';
import scene10 from '../assets/image/scene/10_scene.jpg';

export const DATA = [
	{
    rank: 1,
    img: poster1,
    title: '범죄도시 4',
    year: '2023',
    country: '한국',
    average: '3.0',
    percent: '30%',
    audience: '9122000',
    scene: scene1,
    original_title: '범죄도시4',
    genre: '범죄/액션',
    viewing_time: '1시간 49분',
    age: '15세',
    intro: '신종 마약 사건 3년 뒤, 괴물형사 \'마석도\'(마동석)와 서울 광수대는 배달앱을 이용한 마약 판매 사건을 수사하던 중 수배 중인 앱 개발자가 필리핀에서 사망한 사건이 대규모 온라인 불법 도박 조직과 연관되어 있음을 알아낸다.\n\n필리핀에 거점을 두고 납치, 감금, 폭행, 살인 등으로 대한민국 온라인 불법 도박 시장을 장악한 특수부대 용병 출신의 빌런 \'백창기\'(김무열)와 한국에서 더 큰 판을 짜고 있는 IT업계 천재 CEO \'장동철\'(이동휘).\n\n\'마석도\'는 더 커진 판을 잡기 위해 \'장이수\'(박지환)에게 뜻밖의 협력을 제안하고 광역수사대는 물론, 사이버수사대까지 합류해 범죄를 소탕하기 시작하는데...\n\n나쁜 놈 잡는데 국경도 영역도 제한 없다!\n업그레이드 소탕 작전! 거침없이 싹 쓸어버린다!',
  },
  {
    rank: 2,
    img: poster2,
    title: '쿵푸팬더 4',
    year: '2024',
    country: '미국, 중국',
    average: '2.9',
    percent: '1.2%',
    audience: '1712000',
    scene: scene2,
    original_title: 'Kung Fu Panda 4',
    genre: '애니메이션/액션/모험/코미디',
    viewing_time: '1시간 34분',
    age: '전체',
    intro: '오랜만이지! 드림웍스 레전드 시리즈 마침내 컴백!\n\n마침내 내면의 평화... 냉면의 평화...가 찾아왔다고 믿는 용의 전사 \'포\'. 이젠 평화의 계곡의 영적 지도자가 되고, 자신을 대신할 후계자를 찾아야만 한다.\n\n"이제 용의 전사는 그만둬야 해요?"\n\n용의 전사로의 모습이 익숙해지고 새로운 성장을 하기보다 지금 이대로가 좋은 \'포\'. 하지만 모든 쿵푸 마스터들의 능력을 그대로 복제하는 강력한 빌런 \'카멜레온\'이 나타나고 그녀를 막기 위해 정체를 알 수 없는 쿵푸 고수 \'젠\'과 함께 모험을 떠나게 되는데... 포는 가장 강력한 빌런과 자기 자신마저 뛰어넘고 진정한 변화를 할 수 있을까?',
  },
  {
    rank: 3,
    img: poster3,
    title: '혹성탈출: 새로운 시대',
    year: '2024',
    country: '미국',
    average: '3.2',
    percent: '13%',
    audience: '1430000',
    scene: scene3,
    original_title: 'Kingdom of the Planet of the Apes',
    genre: '액션/SF',
    viewing_time: '2시간 25분',
    age: '12세',
    intro: '인류의 시대는 끝났고, 세상의 주인이 바뀌었다!\n\n진화한 유인원과 퇴화된 인간들이 살아가는 땅. 유인원 리더 \'프록시무스\'는 완전한 군림을 위해 인간들을 사냥하며 자신의 제국을 건설한다. 한편, 또 다른 유인원 \'노아\'는 우연히 숨겨진 과거의 이야기와 \'시저\'의 가르침을 듣게 되고, 의문의 한 인간 소녀와 함께 자유를 향한 여정을 시작하게 되는데...\n\n美 버라이어티 선정 2024년 최고의 기대작\n<아바타: 물의 길> 제작진 x <메이즈 러너> 웨스 볼 감독\n5월 8일, 압도적 비주얼 스펙터클을 경험하라!',
  },
  {
    rank: 4,
    img: poster4,
    title: '포켓몬스터: 성도지방 이야기, 최종장',
    year: '2001',
    country: '일본',
    average: '3.1',
    percent: '0.6%',
    audience: '136000',
    scene: scene4,
    original_title: 'ポケットモンスター「ジョウト編」',
    genre: '애니메이션/모험/가족',
    viewing_time: '1시간 23분',
    age: '전체',
    intro: '결승 토너먼트에서 만난 숙명의 라이벌, \'지우\' vs \'바람\'! 성도지방에서 8개의 배지를 모두 모아 은빛대회에 참가한 \'지우\' 결성 토너먼트에서 숙명의 라이벌, \'바람\'을 마주한다.\n\n"이 \'바람\'님의 라이벌이 되기엔 물 건너가도 한~참 물 건너간 것 같은데?"\n\n언제나 \'지우\'를 얕보며 한 발짝 앞서 나갔던 \'바람\'이지만 포켓몬을 향한 열정이라면 \'지우\'도 지지 않는다. 태초마을을 떠날 때부터 포켓몬마스터의 꿈을 꾼 두 사람 수많은 모험과 만남으로 쌓아온 각자의 성과를 성도리그에서 확인하게 된다. 과연 이 배틀의 승자는...?',
  },
  {
    rank: 5,
    img: poster5,
    title: '스턴트맨',
    year: '2024',
    country: '미국',
    average: '3.4',
    percent: '0.7%',
    audience: '191000',
    scene: scene5,
    original_title: 'The Fall Guy',
    genre: '액션/코미디/드라마/스릴러',
    viewing_time: '2시간 6분',
    age: '12세',
    intro: '사람도 구하고, 영화도 구하고, X도 구하려다 X됐다...!\n\n잠수 이별을 택하고 후회뿐인 날을 보내던 스턴트맨 \'콜트\'(라이언 고슬링)\n영화감독이 된 전 여친 \'조디\'(에밀리 블런트)의 촬영장에 복귀하며 아련한 재회를 기대했\n지만... 갑자기 주연배우가 사라지고 콜트는 우선 그부터 찾아야만 한다!\n\n<데드풀 2> 감독이 말아주는 코미디, 액션, 로맨스 장르 풀코스\n액션도 터지고, 사랑도 터지고, 웃음도 터진다!',
  },
  {
    rank: 6,
    img: poster6,
    title: '악마와의 토크쇼',
    year: '2023',
    country: '호주, 아랍 에미리트 연합국',
    average: '3.3',
    percent: '1.8%',
    audience: '21000',
    scene: scene6,
    original_title: 'Late Night With the Devil',
    genre: '공포',
    viewing_time: '1시간 26분',
    age: '15세',
    intro: '<핼러윈 특집 생방송 \'올빼미 쇼\'> - 오늘의 큐시트\n1부 출연자 - 영매 VS. 영능력자 사냥꾼\n"기적의 사나이라 불리는 영매,\n초자연 현상의 실체를 밝히는 마술사 출신 회의론자. 과연 진실은?"\n\n*중간 광고 후 2부 시작*\n\n2부 출연자 - 악마에게 빙의된 소녀 & [악마와의 대화] 저술한 초심리학자\n"사탄교회 집단자살에서 유일하게 살아남은 소녀,\n악마에게 빙의됐다는 것이 사실인지 현장 검증!"\n\n1977년 핼러윈 전날 밤, 시청률을 위해서라면 일단 틀고 보는 방송국 놈들 때문에 누구도 예상하지 못한 방송사고 발생!\n그리고 마침내 미국 전역을 충격에 빠트렸던 그날 밤의 생방송 \'악마와의 토크쇼\' 녹화영상이 최근에 발견됐는데...\n\n47년간 숨겨진, 절대 생중계돼서는 안 될 최악의 토크쇼가 마침내 공개된다.\n그동안 공개되지 않은 비하인드 영상과 함께!',
  },
  {
    rank: 7,
    img: poster7,
    title: '가필드 더 무비',
    year: '2024',
    country: '영국, 미국',
    average: '',
    percent: '6.4%',
    audience: '1001',
    scene: scene7,
    original_title: 'The Garfield Movie',
    genre: '애니메이션/모험/코미디',
    viewing_time: '1시간 41분',
    age: '전체',
    intro: "세상귀찮 집냥이, 바쁘고 험난한 세상에 던져졌다!\n\n집사 '존'과 반려견 '오디'를 기르며 평화로운 나날을 보내던 집냥이 '가필드'. 어느 날, 험악한 길냥이 무리에게 납치당해 냉혹한 거리로 던져진다. 돌봐주는 집사가 없는 집 밖 세상은 너무나도 정신없게 돌아가고 길에서 우연히 다시 만난 아빠 길냥이 '빅'은 오히려 '가필드'를 위기에 빠지게 하는데...\n\n험난한 세상, 살아남아야 한다!",
  },
  {
    rank: 8,
    img: poster8,
    title: '극장판 하이큐!! 쓰레기장의 결전',
    year: '2023',
    country: '일본',
    average: '',
    percent: '22%',
    audience: '1701',
    scene: scene8,
    original_title: '劇場版 ハイキュー!! ゴミ捨て場の決戦',
    genre: '애니메이션/스포츠',
    viewing_time: '1시간 24분',
    age: '전체',
    intro: "봄철 고교 배구대회 미야기현 대표 결정전. 1회전과 2회전에서 우승 후보를 차례로 꺾은 카라스노 고등학교는 마침내 3회전에서 인연의 라이벌 네코마 고등학교와 맞붙게 된다. 공식 경기에서 처음으로 대결하는 두 고등학교, 통칭 까마귀 VS 고양이 '쓰레기장의 결전'. 약속의 땅에서 '한 번 더'가 없는 싸움이 드디어 시작된다!",
  },
  {
    rank: 9,
    img: poster9,
    title: '꼬마참새 리차드: 신비한 보석 탐험대',
    year: '2023',
    country: '독일, 벨기에, 노르웨이',
    average: '2.7',
    percent: '0.7%',
    audience: '26000',
    scene: scene9,
    original_title: 'Richard the Stork and the Mystery of the Great Jewel',
    genre: '애니메이션/모험/가족',
    viewing_time: '1시간 24분',
    age: '전체',
    intro: "황새가 키운 최강 꼬마참새 '리차드'가 돌아왔다!\n\n아프리카의 해변에서 황새 가족의 따듯한 보살핌 속에 뛰어난 비행 실력을 지닌 용감한 참새로 자란 '리차드'. 어느 날 '리차드'는 친구인 앵무새 '키키', 올빼미 '올가'와 함께 우연히 위험천만한 사막을 지나 신비로운 도시에 도착하게 된다. 하지만 그들은 곧 공작새 '자마노'의 부하인 대머리황새들에게 공격을 당하고 도시 참새의 리더 '사미아'의 도움을 받아 가까스로 위기에서 벗어난다. 자신을 구해준 도시 참새들이 탐욕스러운 '자마노'에게 잡혀 있다는 사실을 알게 된 '리차드'와 친구들은 이제 그들을 구하기 위해 전설 속 보석을 찾기로 결심하는데...\n\n더 빠르게! 더 신나게! 더 높게!\n신비한 보석을 찾아 아프리카 속으로 훨훨 날아볼까?",
  },
  {
    rank: 10,
    img: poster10,
    title: '남은 인생 10년',
    year: '2022',
    country: '일본',
    average: '3.2',
    percent: '0.9%',
    audience: '487000',
    scene: scene10,
    original_title: '余命10年',
    genre: '드라마/로맨스',
    viewing_time: '2시간 4분',
    age: '12세',
    intro: "매일 밤, 눈 감기가 두려웠던 난치병 환자 '마츠리'\n매일 아침, 눈 뜨기가 두려웠던 외톨이 '카즈토'\n운명은 정반대에 있던 두 사람을 마주 보게 한다.\n\n처음 만난 봄,\n많이 웃은 여름,\n더욱 깊어진 가을,\n소중해서 아팠던 겨울까지\n남은 인생을 진정으로 사랑하게 해준 너에게 감사해",
  },
];

export default DATA;